rvm: '2.2.0'

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install -g bower
  - bower install

script:
  - bundle exec bin/rake db:create
  - bundle exec bin/rake db:migrate
  - bundle exec rspec spec

deploy:
  provider: heroku
  api_key: 50704842-ce26-4d6b-a8a0-d2db93c9f3a0
  app: young-reaches-5564